id: P003054
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:37:20.926585
source_metadata:
  id: bdr:W23829
  title: ཐུགས་རྗེ་ཆེན་པོ་གསང་བ་འདུས་པའི་ཆོས་སྐོར།
  author: ''
  volumes:
    aead57d34eb74b4881221fa2a18dc906:
      image_group_id: I1KG9698
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
