id: I0F98303C
legacy_id: P003054
ocr_import_info:
  bdrc_scan_id: W23829
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T23:34:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:50:15.822876+00:00'
last_modified: 2022-09-02 12:50:24.280292
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23829
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23829
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུགས་རྗེ་ཆེན་པོ་གསང་བ་འདུས་པའི་ཆོས་སྐོར།
  author: རཏྣ་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7360040977383582
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1KG9698:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9698
      total_pages: 224
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9698.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7360040977383582
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
