id: I0F98303C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:35:43+00:00'
last_modified: '2022-06-07T17:14:52.099497+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23829
  title: ཐུགས་རྗེ་ཆེན་པོ་གསང་བ་འདུས་པའི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    37D3:
      image_group_id: I1KG9698
      title: ''
      total_pages: 224
      order: 1
      base_file: 37D3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
